spring:
  docker:
    compose:
      enabled: false

kafka:
  bootstrap-servers: rc1a-832o9qir77b47g7g.mdb.yandexcloud.net:9091,rc1b-7864vav1e5abhngd.mdb.yandexcloud.net:9091,rc1d-t920tc533mtp4336.mdb.yandexcloud.net:9091
  schema-registry-url: https://srngiim1anfoggfj0qdb.schema-registry.yandexcloud.net:443

# определяет к какой кафке обращаться
local-env: false
