server:
  port: 9193

spring:
  docker:
    compose:
      enabled: false

kafka:
  bootstrap-servers: ${BOOTSTRAP_SERVERS}
  schema-registry-url: ${SCHEMA_REGISTRY_URL}
  security-protocol: SASL_SSL
  sasl-mechanism: SCRAM-SHA-512
  sasl-jaas-config: org.apache.kafka.common.security.scram.ScramLoginModule required username="kafka-user" password="ваш-пароль";
  ssl-truststore-location: /ca/CA.pem
  ssl-truststore-password: qwerty
  # consumer
  example-topic:
    topic: orders
    group-id: orders.1
    enable: true
    enable-auto-commit: true
    auto-commit-interval-ms: 1000
    max-poll-records: 1
    poll-duration-ms: 1000
  # producer
  example-event:
    topic: orders
    acks: "all"
    retries: 3
    retry-backoff-ms: 1000
    enable-idempotence: true

local-env: ${LOCAL_ENV}
