security.protocol=SASL_SSL
ssl.truststore.location=/etc/kafka/secrets/truststore.jks
ssl.truststore.password=qwerty
sasl.mechanism=PLAIN
sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="admin-secret";
