version: '3.8'

networks:
  kafka-net:
    driver: bridge
    name: kafka-cluster-network

x-kafka-common-env: &kafka-common-env
  KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
  KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
  KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:SASL_SSL,EXTERNAL:SASL_SSL

  # SSL settings
  KAFKA_SSL_KEYSTORE_TYPE: JKS
  KAFKA_SSL_TRUSTSTORE_TYPE: JKS
  KAFKA_SSL_TRUSTSTORE_PASSWORD: qwerty
  KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: "HTTPS"
  # internal
  KAFKA_LISTENER_NAME_INTERNAL_SSL_KEYSTORE_LOCATION: /etc/kafka/secrets/keystore.jks
  KAFKA_LISTENER_NAME_INTERNAL_SSL_KEYSTORE_PASSWORD: qwerty
  KAFKA_LISTENER_NAME_INTERNAL_SSL_KEY_PASSWORD: qwerty
  KAFKA_LISTENER_NAME_INTERNAL_SSL_TRUSTSTORE_LOCATION: /etc/kafka/secrets/truststore.jks
  KAFKA_LISTENER_NAME_INTERNAL_SSL_TRUSTSTORE_PASSWORD: qwerty
  # external
  KAFKA_LISTENER_NAME_EXTERNAL_SSL_KEYSTORE_LOCATION: /etc/kafka/secrets/keystore.jks
  KAFKA_LISTENER_NAME_EXTERNAL_SSL_KEYSTORE_PASSWORD: qwerty
  KAFKA_LISTENER_NAME_EXTERNAL_SSL_KEY_PASSWORD: qwerty
  KAFKA_LISTENER_NAME_EXTERNAL_SSL_TRUSTSTORE_LOCATION: /etc/kafka/secrets/truststore.jks
  KAFKA_LISTENER_NAME_EXTERNAL_SSL_TRUSTSTORE_PASSWORD: qwerty

  # SASL settings
  KAFKA_ZOOKEEPER_SASL_CLIENT: 'true'
  KAFKA_ZOOKEEPER_SET_ACL: 'true'
  KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
  KAFKA_SASL_MECHANISM_CONTROLLER_PROTOCOL: PLAIN
  KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
  #KAFKA_INTER_BROKER_LISTENER_NAME: SASL_SSL
  KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
  KAFKA_SUPER_USERS: User:admin
  KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/secrets/kafka_server_jaas.conf"
  #KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: SASL_SSL:SASL_SSL,OUTBOUND:SASL_SSL
  KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "false"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: zookeeper
    platform: linux/arm64
    networks:
      - kafka-net
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      KAFKA_OPTS: >-
        -Djava.security.auth.login.config=/etc/zookeeper/secrets/zookeeper.sasl.jaas.conf
        -Dzookeeper.authProvider.sasl=org.apache.zookeeper.server.auth.SASLAuthenticationProvider
        -Dzookeeper.allowSaslFailedClients=false
        -Dzookeeper.requireClientAuthScheme=sasl
    ports:
      - "2181:2181"
    volumes:
      - ./zookeeper.sasl.jaas.conf:/etc/zookeeper/secrets/zookeeper.sasl.jaas.conf

  kafka1:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka1
    platform: linux/arm64
    depends_on:
      - zookeeper
    networks:
      - kafka-net
    ports:
      - "9092:9092"
    environment:
      <<: *kafka-common-env
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:19092,EXTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka1:19092,EXTERNAL://localhost:9092
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
    volumes:
      - ./kafka1:/etc/kafka/secrets
      - ./admin.properties:/etc/kafka/secrets/admin.properties

  kafka2:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka2
    platform: linux/arm64
    depends_on:
      - zookeeper
    networks:
      - kafka-net
    ports:
      - "9093:9093"
    environment:
      <<: *kafka-common-env
      KAFKA_BROKER_ID: 2
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:19093,EXTERNAL://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka2:19093,EXTERNAL://localhost:9093
    volumes:
      - ./kafka2:/etc/kafka/secrets
      - ./admin.properties:/etc/kafka/secrets/admin.properties

  kafka3:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka3
    platform: linux/arm64
    depends_on:
      - zookeeper
    networks:
      - kafka-net
    ports:
      - "9094:9094"
    environment:
      <<: *kafka-common-env
      KAFKA_BROKER_ID: 3
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:19094,EXTERNAL://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka3:19094,EXTERNAL://localhost:9094
    volumes:
      - ./kafka3:/etc/kafka/secrets
      - ./admin.properties:/etc/kafka/secrets/admin.properties

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    platform: linux/arm64
    networks:
      - kafka-net
    ports:
      - "8080:8080"
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    environment:
      KAFKA_CLUSTERS_0_NAME: local-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka1:19092,kafka2:19093,kafka3:19094
      KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: SSL
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_TRUSTSTORE_LOCATION: /etc/kafka/secrets/truststore.jks
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_TRUSTSTORE_PASSWORD: qwerty
      DYNAMIC_CONFIG_ENABLED: "true"
    volumes:
      - ./ca:/etc/kafka/secrets
